# Generated by Django 4.0.3 on 2022-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersCarForSell',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_car_name', models.CharField(max_length=200)),
                ('customer_number', models.CharField(max_length=150)),
                ('customer_location', models.CharField(max_length=300)),
                ('customer_car_model', models.CharField(max_length=50)),
                ('customer_car_color', models.CharField(max_length=50)),
                ('customer_uploading_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnSellCars',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=200)),
                ('owner_number', models.CharField(max_length=150)),
                ('owner_location', models.CharField(max_length=300)),
                ('car_model', models.CharField(max_length=50)),
                ('car_color', models.CharField(max_length=50)),
                ('uploading_date', models.DateField()),
            ],
        ),
    ]
