# Generated by Django 4.0.3 on 2022-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerscarforsell',
            name='customer_car_image',
            field=models.ImageField(default='', upload_to='customercar/'),
        ),
        migrations.AddField(
            model_name='ownsellcars',
            name='image',
            field=models.ImageField(default='', upload_to='ownercars/'),
        ),
    ]
