# Generated by Django 4.0.3 on 2022-09-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0003_customerscarforsell_customer_car_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerscarforsell',
            name='customer_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ownsellcars',
            name='owner_location',
            field=models.TextField(),
        ),
    ]
